---
deployment:
  tasks:
    - export HOME=/home/amoshwz1
    - export REPO=/home/amoshwz1/repositories/amoshow_backend
    - /bin/cp -R $REPO/app $HOME/
    - /bin/cp -R $REPO/bootstrap $HOME/
    - /bin/cp -R $REPO/config $HOME/
    - /bin/cp -R $REPO/routes $HOME/
    - /bin/cp -R $REPO/resources $HOME/
    - /bin/cp $REPO/artisan $HOME/
    - /bin/cp -R $REPO/public/. $HOME/public_html/
